- Docker/Configuration/Input/File.php
- Docker/StorageApi/Reader.php
- Tests/Docker/StorageApiReaderTest.php
Added option to filter files by runId of the parent of the current job.
> Filter parent

- Docker/Executor.php
- Docker/Image/Builder/ImageBuilder.php
- Job/Executor.php
- Tests/Docker/ExecutorTest.php
- Tests/Docker/ImageBuilderTest.php
- Tests/Functional/ImageBuilderTest.php
- apiary.apib
Oddělení parametrů, které se neukládají do configu
> Volatile config2

- Docker/Configuration/Output/Table/Manifest.php
- Docker/StorageApi/Writer.php
- Tests/Docker/OutputTableConfigurationTest.php
- Tests/Docker/OutputTableManifestConfigurationTest.php
- Tests/Docker/StorageApiWriterTest.php
> Default bucket and destinations

- Tests/Docker/ExecutorTest.php
- Tests/Docker/StorageApiReaderTest.php
- Tests/Docker/StorageApiWriterTest.php
- Tests/Functional/FunctionalTest.php
- Tests/Functional/LoggerTest.php
- Tests/Job/Metadata/JobFactoryTest.php
- bootstrap.php
- build.xml
**Bude treba pridat novu environment premennu.**
Nastavene:
> Add Storage API URL to its Client instances

- Docker/Configuration/Component.php
- Docker/Runner/DataLoader.php
- Service/Runner.php
- Tests/Docker/ImageConfigurationTest.php
- Tests/Runner/DataLoaderTest.php
- composer.json
- composer.lock
Add option for component to work with input files stored in S3.
> Staging storage

- Docker/StorageApi/Writer.php
- Resources/schemas/configuration.json
- Tests/Docker/StorageApiSlicedWriterTest.php
- composer.lock
Reverts keboola/docker-bundle#103
> Revert "Revert "feat(writer): sliced tables ""

- Docker/Container.php
- Docker/Runner/DataDirectory.php
- Exception/WeirdException.php
- Service/Runner.php
- Tests/Functional/DataLoaderTest.php
- Tests/Functional/WeirdBugErrorTest.php
- Tests/Runner/DataDirectoryTest.php
feat: retry on chown device mapper error
> feat: retry on chown timeout

- composer.lock
https://github.com/keboola/syrup/pull/99
> Update syrup to version 5.1.1 (bugfix)

- composer.lock
related to: https://github.com/keboola/syrup/pull/101
> Update syrup to version 5.1.2

- Docker/Runner/DataLoader.php
- Docker/StorageApi/Writer.php
- Tests/Docker/StorageApiReaderTest.php
- composer.json
- composer.lock
souvisí s https://github.com/keboola/connection/issues/515#issuecomment-292141255
> deps update - file uploads with download friendly names

- Docker/Image.php
- Docker/Image/Builder/ImageBuilder.php
- Docker/Runner/DataDirectory.php
- Docker/Runner/DataLoader/DataLoader.php
- Docker/Runner/DataLoader/DataLoaderInterface.php
- Docker/Runner/DataLoader/NullDataLoader.php
- Docker/Runner/ImageCreator.php
- Docker/StorageApi/Writer.php
- Service/LoggersService.php
- Tests/Docker/ImageBuilderTest.php
- Tests/Docker/ImageTest.php
- Tests/Docker/StorageApiHeadlessWriterTest.php
- Tests/Docker/StorageApiSlicedWriterTest.php
- Tests/Docker/StorageApiWriterMetadataTest.php
- Tests/Docker/StorageApiWriterStaticTest.php
- Tests/Docker/StorageApiWriterTest.php
- Tests/Functional/AWSElasticContainerRegistryTest.php
- Tests/Functional/DataLoaderMetadataTest.php
- Tests/Functional/DataLoaderTest.php
- Tests/Functional/DockerHubPrivateRepositoryTest.php
- Tests/Functional/ImageBuilderTest.php
- Tests/Functional/ImageCreatorTest.php
- Tests/Functional/QuayIOPrivateRepositoryTest.php
- Tests/Functional/QuayIORepositoryTest.php
- Tests/Functional/RunnerTest.php
- Tests/Runner/DataDirectoryTest.php
and remove dependency on Monolog where possible
> refactor: replace NullHandler with NullLogger

- Docker/Image/AWSElasticContainerRegistry.php
- Docker/Image/Builder/ImageBuilder.php
- Docker/Image/DockerHub/PrivateRepository.php
- Docker/Image/QuayIO/PrivateRepository.php
Mala kozmeticka uprava. Vsimol som si to uz davnejsie, no prislo mi to znovu na rozum, ked sa upravovalo teraz to escapovanie hesla.
Tie images su vlastne identicke, akurat v jednom je naviac `dind` command, ktory nam netreba. A nechcem aby sa z toho stal "cargo cult" :)
> Remove pulling image with dind (standard docker is enough)

- .travis.yml
- Controller/ApiController.php
- Controller/PublicController.php
- Resources/config/routing.yml
- Tests/Controller/EncryptTest.php
- Tests/Controller/PublicControllerTest.php
- apiary.apib
https://github.com/keboola/docker-bundle/issues/182
https://github.com/keboola/docker-bundle/issues/192
> feat: single encryption endpoint

- Docker/Container.php
- Docker/Runner/DataDirectory.php
- Service/Runner.php
- Tests/Docker/ContainerTest.php
- Tests/Functional/RunnerTest.php
> feat: force container user instead of normalising permissions afterwards

- composer.json
- composer.lock
> feat: changed_since 

- Docker/Container.php
- Docker/Container/Process.php
- Tests/Functional/ContainerErrorHandlingTest.php
- Tests/Functional/ContainerUtf8SanitizationTest.php
> feat: sanitize utf-8 output from container

- Docker/JobDefinitionParser.php
- Job/Executor.php
- Tests/Docker/JobDefinitionParserTest.php
- Tests/Functional/JobExecutorInlineConfigTest.php
- Tests/Functional/JobExecutorInlineConfigWithConfigIdTest.php
- Tests/Functional/JobExecutorStoredConfigMultipleRowsTest.php
> fix: stored config missing config id for default_bucket

- Controller/ApiController.php
- Controller/PublicController.php
- Docker/Runner/Environment.php
- Job/Executor.php
- Resources/config/services.yml
- Tests/Controller/ApiControllerTest.php
- Tests/Controller/PublicControllerTest.php
- Tests/Functional/EncryptionTest.php
- Tests/Functional/JobExecutorInlineConfigTest.php
- Tests/Functional/JobExecutorInlineConfigWithConfigIdTest.php
- Tests/Functional/JobExecutorStoredConfigMultipleRowsTest.php
- Tests/Functional/JobExecutorStoredConfigTest.php
- Tests/Runner/EnvironmentTest.php
- docker-tests/parameters.yml
feat: pass KBC_STACKID to component
refactor: remove stack_id parameter
pri merge doplnit dokumentaci https://developers.keboola.com/extend/common-interface/environment/#environment-variables
fixes https://github.com/keboola/docker-bundle/issues/231
> KBC_STACKID

- Docker/Configuration/Container.php
- Docker/Runner/Authorization.php
- Service/Runner.php
- Tests/Controller/ActionControllerTest.php
- Tests/Functional/EncryptionTest.php
- Tests/Functional/RunnerTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/ConfigFileTest.php
fixes https://github.com/keboola/docker-bundle/issues/232
> feat: support oauth api version 3

- Docker/Component.php
- Docker/Configuration/Component.php
- Docker/Runner/Environment.php
- Tests/Docker/ImageConfigurationTest.php
- Tests/Functional/RunnerTest.php
- Tests/Runner/EnvironmentTest.php
> refactor: remove environment injection

- Docker/Runner/WorkingDirectory.php
- Tests/Runner/WorkingDirectoryTest.php
https://keboola.slack.com/archives/C09U3R1J4/p1524979187000062
> fix(WorkingDirectory): chmod & chown performance tuning

- Docker/Runner/WorkingDirectory.php
- Tests/Runner/WorkingDirectoryTest.php
fix normalize test so that it gets actually executed
add check to make sure that normalize is executed
add logging to normalize command
> fix retry test

- Docker/Container.php
- Docker/Runner/Limits.php
- Resources/config/services.yml
- Service/Runner.php
- Tests/Docker/ContainerTest.php
- Tests/Functional/ContainerErrorHandlingTest.php
- Tests/Functional/ContainerUtf8SanitizationTest.php
- Tests/Functional/DebugModeTest.php
- Tests/Functional/EncryptionTest.php
- Tests/Functional/JobExecutorInlineConfigTest.php
- Tests/Functional/JobExecutorInlineConfigWithConfigIdTest.php
- Tests/Functional/JobExecutorStoredConfigMultipleRowsTest.php
- Tests/Functional/JobExecutorStoredConfigTest.php
- Tests/Functional/LoggerTest.php
- Tests/Functional/NetworkTest.php
- Tests/Functional/RunnerConfigRowsTest.php
- Tests/Functional/RunnerTest.php
- Tests/Functional/UsageFileTest.php
- Tests/Runner/LimitsTest.php
- docker-tests/parameters.yml
feat: make cpu limit adjustable in parameters
> refactor: use limits class

- Job/Executor.php
- Tests/Functional/JobExecutorStoredConfigMultipleRowsTest.php
> fix: all disabled rows

- Controller/ActionController.php
- Docker/Runner/DataLoader/DataLoader.php
- Docker/Runner/DataLoader/DataLoaderInterface.php
- Docker/Runner/DataLoader/NullDataLoader.php
- Job/Executor.php
- Service/Runner.php
> fix: remove unused features

- Docker/JobDefinitionParser.php
- Tests/Docker/JobDefinitionParserTest.php
fixes https://github.com/keboola/docker-bundle/issues/80
fixes https://github.com/keboola/docker-bundle/issues/254
> processor validation

- Tests/Docker/StorageApiReaderTest.php
- composer.json
- composer.lock
IM: Removed attributes from table manifest: indexed_columns, rows_count, data_size_bytes, is_alias, attributes
- IM: empty where_operator is now equal to default where_operator
- OM: Removed unused public methods getClient, setClient, setMetadataClient, getFeatures, hasFeature, getLogger, setLogger
- OM: delete_where_operator is now equal to default delete_where_operator
> imom update

- Docker/Runner/StateFile.php
- Service/Runner.php
- Tests/Functional/EncryptionTest.php
- Tests/Functional/RunnerConfigRowsTest.php
- Tests/Functional/RunnerTest.php
- Tests/Functional/UsageFileTest.php
- Tests/Runner/StateFileTest.php
- bootstrap.php
- build.xml
- docker-tests/run-job/run-job.sh
alternative to https://github.com/keboola/docker-bundle/pull/249
> feat: encrypt configuration state when saving, fixes #248

- Docker/Configuration/Adapter.php
- Docker/Configuration/State/Adapter.php
- Docker/Runner/ConfigFile.php
- Tests/Docker/Configuration/ConfigurationAdapterTest.php
- Tests/Docker/Configuration/ContainerConfigurationTest.php
- Tests/Executor/JobExecutorInlineConfigTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/ConfigFileTest.php
fixes https://github.com/keboola/docker-bundle/issues/318
no nejak extra happy z toho nejsem
> fix: empty props encoded as object

- Tests/Runner/UsageFileTest.php
- src/Docker/Runner/UsageFile/UsageFile.php
> fix: do not store empty usage

- Tests/Runner/OutputTest.php
- Tests/Runner/RunnerTest.php
- Tests/Runner/StateFileTest.php
- src/Docker/Runner.php
- src/Docker/Runner/Output.php
- src/Docker/Runner/StateFile.php
fixes #290 
je tam velkej diff testu, ale schvalne jsem je udelal naprd jako prochazejici a pak jako failujici, takze v b53bdf06dd1e29c9cfc44cfb2fb57875ae5ffcc1 je videt ta zmena chovani
> Output mapping - state fix

- composer.json
- composer.lock
update na poslední output mapping a storage api klient. nevím, jestli se někde neduplikuju s tvejma pull requestama?
> feat: compress output mapping

- Resources/config/services.yml
- Tests/BaseContainerTest.php
- Tests/Docker/Container/LoggerTest.php
- composer.lock
- src/Monolog/Handler/StorageApiHandler.php
- src/Service/StorageApiService.php
feat: pass events from storage api client to runner
> storage api client logger

- src/Docker/Image/AWSElasticContainerRegistry.php
- src/Exception/RetryableLoginException.php
feat: retry get authorization token
> quickfix: retry get auth token

- .gitignore
- Tests/Runner/RunnerTest.php
- composer.json
- composer.lock
- src/Docker/Runner/DataLoader/DataLoader.php
removed support for parallel-output-mapping-load feature, deferred loads are now the only behavior
> feat: update output mapping

- .gitignore
- Tests/Runner/RunnerTest.php
- composer.json
- composer.lock
- src/Docker/Runner/DataLoader/DataLoader.php
refactor: removed support for parallel-output-mapping-load feature
feat: deferred loads are now the only behavior
> update output mapping take2

- composer.lock
https://github.com/keboola/output-mapping/pull/34
> fix: handle CSV error 

- .travis.yml
- composer.json
- composer.lock
- src/Docker/Runner/DataLoader/DataLoader.php
- update input mapping to `^8.0` and use `Reader\Options\InputTablesOptions` in `DataLoader`
- configure composer to use PHP 5.6 (for local updating)
- removed branch limit in `.travis.yml`
> feat: update input mapping

- Tests/Docker/Configuration/ImageConfigurationTest.php
- src/Docker/Configuration/Image.php
fixes https://github.com/keboola/docker-bundle/issues/387
> feat: allow image digest

- Tests/Runner/LimitsTest.php
- src/Docker/Runner/Limits.php
fixes https://github.com/keboola/docker-bundle/issues/403
> feat: project settable memory limits

- Tests/BaseContainerTest.php
- Tests/Docker/Container/ContainerErrorHandlingTest.php
- src/Docker/Container.php
> fix: show effective memory limit in OOM error

- src/Docker/Runner/ImageCreator.php
fixes https://github.com/keboola/docker-bundle/issues/360
the message was not recorded anyway
> fix: remove misleading debug message

- Tests/Docker/ComponentTest.php
- src/Docker/Component.php
- src/Docker/Configuration/Image.php
better error message on invalid component definition, fixes https://github.com/keboola/docker-bundle/issues/336, fixes https://github.com/keboola/docker-bundle/issues/335
> better message for invalid components

- composer.lock
fix: im/om update to fix https://github.com/keboola/input-mapping/issues/34
> im/om update 

- src/Docker/Runner.php
> fix: container id/name generation

- Tests/Controller/ActionControllerTest.php
- build.xml
@ondrejhlavacek koukni prosimte na https://jenkins.keboola.com/view/Runner/ jestli tam neuvidis nejakou zjevnou botu nebo neco, co jsem zapomnel nez to zacnu spoustet 
parameters.yml jsem do bucketu `jenkins-devel-syrup-configs` zkopiroval
> chore: get parameters

- .travis.yml
- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
- Tests/Runner/RunnerTest.php
- composer.lock
- src/Docker/Image/AWSElasticContainerRegistry.php
fix: update IM to hotfix https://github.com/keboola/internal/issues/137
> vendor update

- Tests/Executor/JobExecutorInlineConfigTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/Runner/Authorization.php
Reverts keboola/docker-bundle#442
> Revert "Throw user exception if oauth_api version 2 is used"

- Tests/Executor/JobExecutorInlineConfigTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/Runner/Authorization.php
Changes:
- Reverts keboola/docker-bundle#444 
- Fixes auth for Generic Ex (injected credentials)
> Throw user exception if oauth_api version 2 is used + Fix for injected credentials

- composer.json
- composer.lock
feat: update im to support table search by tag
> feat: update im to support table search by tag

- Tests/Runner/RunnerTest.php
- src/Docker/Runner.php
fix: do not run processors when there is no IM/OM (mainly sync actions)
fixes: #447
> processors and sync actions

- Tests/Runner/RunnerTest.php
> tests: stabilize, fixes #451

- src/Docker/Runner.php
> feat: add project id container label

- Tests/Docker/Container/LoggerTest.php
- composer.lock
- docker-tests/config_dev.yml
- docker-tests/config_prod.yml
fixes: 
- COM-50 - https://github.com/keboola/gelf-server/releases/tag/2.0.1, 
- PS-213 - https://github.com/keboola/input-mapping/releases/tag/8.2.0, 
- security update - replaces https://github.com/keboola/docker-bundle/pull/462
> vendor update 

- Resources/Elasticsearch/mapping.json
- Tests/Docker/Configuration/ContainerConfigurationTest.php
- src/Docker/Configuration/Container.php
https://keboola.atlassian.net/browse/PS-334
> Fields for variable values

- Tests/Runner/VariableResolverTest.php
- apiary.apib
- src/Docker/VariableResolver.php
fix: exception message
https://keboola.atlassian.net/browse/PS-428
> docs: update API docs with api call attributes

- Tests/Runner/VariableResolverTest.php
- composer.json
- composer.lock
- src/Docker/VariableResolver.php
fix: default escaping set to JSONish
fix: handle invalid configuration after replacement
https://keboola.atlassian.net/browse/PS-419
> JSON escaping

- composer.lock
to fix logging https://github.com/keboola/syrup/releases/tag/11.3.3
> vendor update to fix logging

- Tests/Docker/Image/ImageBuilderTest.php
https://keboola.atlassian.net/browse/PS-681
> tests: use new repository

- composer.json
- composer.lock
Suvisi s https://keboola.atlassian.net/browse/PS-555
> Updated input mapping to refactored version

- Tests/Controller/ApiControllerTest.php
- apiary.apib
- src/Controller/ApiController.php
- src/Resources/config/routing.yml
https://keboola.atlassian.net/browse/PS-675
test se musi spustit rucne - v `docker-tests`
> feat: API call to return sum of jobs duration for project

- composer.json
- composer.lock
https://keboola.atlassian.net/browse/PS-718
> update storage client

- Tests/Controller/ApiControllerTest.php
- src/Resources/config/routing.yml
https://keboola.atlassian.net/browse/PS-693
> fix: stats call according to the spec

- Tests/Controller/ApiControllerTest.php
- apiary.apib
- src/Controller/ApiController.php
- src/Resources/config/routing.yml
https://keboola.atlassian.net/browse/PS-776
> PS-776 Resolve variables request

- Tests/Runner/VariableResolverTest.php
- src/Docker/Runner/VariablesContext.php
- src/Docker/VariableResolver.php
https://keboola.atlassian.net/browse/PS-381
> feat: unresolved variables raise user error

- Tests/Docker/BillingClientTest.php
- Tests/Docker/CreditsCheckerTest.php
- src/Controller/ApiController.php
- src/Docker/BillingClient.php
- src/Docker/CreditsChecker.php
- src/Docker/Runner.php
- src/Exception/BillingClientException.php
- src/Job/Executor.php
https://keboola.atlassian.net/browse/PS-710
> PS-710 Prevent user to start job when no credits are remaining

- Tests/Controller/ApiControllerTest.php
- apiary.apib
- src/Controller/ApiController.php
- src/Resources/config/routing.yml
https://keboola.atlassian.net/browse/PS-818
ten test testProjectStatsDaily je takovej dost na prasaka, protoze jsou v nem schovany dalsi 4, ale ono je to tak komplikovany to nasetupovat, ze jsem to teda nechtel uz delit :/ 
detaily: https://keboola.slack.com/archives/CQB468K63/p1597298126032300
priplacl jsem k tomu odstraneni spatne routy: https://keboola.slack.com/archives/CFVRE56UA/p1597346686099000?thread_ts=1597245972.064500&cid=CFVRE56UA
> Add daily stats call

- Tests/Runner/EnvironmentTest.php
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PS-820
> fix: don't read token from tokeninfo

- Tests/BaseRunnerTest.php
- Tests/Runner/RunnerTest.php
- Tests/backend-specific-tests/ABS/RunnerAbsTest.php
https://keboola.atlassian.net/browse/PS-698
Input mapping, co podporuje abs uz je tam updatnuty, cili to funguje out of the box a dopsal jsem jen testy
> ABS Staging

- Tests/BaseRunnerTest.php
- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- Tests/backend-specific-tests/Synapse/SynapseWorkspaceProviderTest.php
- src/Docker/Runner/DataLoader/DataLoader.php
tests: add synapse integration test
> fix: synapse workspace provider

- Tests/backend-specific-tests/ABS/RunnerAbsTest.php
- composer.lock
follow up to https://github.com/keboola/input-mapping/pull/58
https://keboola.atlassian.net/browse/PS-926
> fix: ABS input mapping key now points to manifest file

- composer.lock
https://keboola.atlassian.net/browse/PS-996
follow up to https://github.com/keboola/output-mapping/pull/53
> update OM to 1.11.1

- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
- Tests/Docker/Image/QuayIORepositoryTest.php
- Tests/Docker/ImageTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/Container.php
- src/Docker/Image.php
- src/Docker/Image/AWSElasticContainerRegistry.php
- src/Docker/Image/DockerHub.php
- src/Docker/Image/QuayIO.php
- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PS-937
V `notice` logech jsem nechal full image Id, ty chodi jen k nam do PT
> feat: show only image name in external logs

- composer.lock
https://keboola.atlassian.net/browse/PS-1010
follow up to https://github.com/keboola/input-mapping/pull/60
> update IM to 9.4.3

- Tests/Docker/BillingClientTest.php
- Tests/Docker/CreditsCheckerTest.php
- src/Docker/BillingClient.php
https://keboola.atlassian.net/browse/PS-1031
fix: credits are not integer
tests: add value provide to CreditsCheckerTest
> Fractional credits

- Tests/Controller/ApiControllerTest.php
- src/Controller/ApiController.php
https://keboola.atlassian.net/browse/PS-1018
> exclude orchestrator from job stats

- Tests/BaseExecutorTest.php
- Tests/Controller/ActionControllerTest.php
- Tests/Executor/JobExecutorInlineConfigTest.php
- src/Controller/ActionController.php
- src/Job/Executor.php
- disable sync actions for readonly user
- add another check so as not to execute jobs if they pass api (e.g. through orchestrator)
https://keboola.atlassian.net/browse/PS-1422
> Readonly role

- Resources/Elasticsearch/mapping.json
- Tests/Controller/ApiControllerTest.php
- composer.json
- composer.lock
- src/Controller/ApiController.php
- src/Resources/config/routing.yml
https://keboola.atlassian.net/browse/PS-1166
K synchronnim akcim jsem to zatim nepridaval (rekli jsme, ze to zatim nebudem resit), schema URL jsem prevzal z connection. Soucasne s tim, je tam pridani do ES indexu https://keboola.atlassian.net/browse/PS-1166, protoze to bez toho nejde.
> branch endpoints

- Tests/Runner/StateFileTest.php
- composer.json
- composer.lock
https://keboola.atlassian.net/browse/PS-1487
testy zacnou prochazet pro novym release IM https://github.com/keboola/input-mapping/pull/64
> update storage API client

- src/Controller/ActionController.php
https://keboola.atlassian.net/browse/PS-1168
Tohle me uteklo a rozbil jsem synchronni akce
https://travis-ci.com/github/keboola/docker-runner-router/jobs/443363522
> fix: broken parameters

- Tests/BaseDataLoaderTest.php
- Tests/BaseExecutorTest.php
- Tests/BaseRunnerTest.php
- Tests/Executor/JobExecutorStoredConfigTest.php
- Tests/backend-specific-tests/ABS/DataLoaderABSTest.php
- Tests/backend-specific-tests/S3/DataLoaderS3Test.php
- bootstrap.php
- composer.lock
- src/Job/Executor.php
https://keboola.atlassian.net/browse/PS-1174
V testech je to strasne nahastroseny, ale zatim moc nevime jak budou dal vypadat ty interfacy, tak se mi to nechce uplne cely prekopavat. Musel jsem pridat master token do konfigurace, protoze branch muze zalozit jen master token.
> Read branch configurations

- apiary.apib
https://keboola.atlassian.net/browse/PS-1178
> update api docs

- src/Controller/ActionController.php
tohle patri jeste k https://github.com/keboola/docker-bundle/pull/519
klasicky jsem zapomnel na sync akce
> sync actions have no branch yet

- Tests/Runner/DataLoaderTest.php
- Tests/backend-specific-tests/Synapse/AbsWorkspaceProviderTest.php
- composer.json
- composer.lock
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/DataLoader/WorkspaceProvider.php
implementation for abs workspace staging
> PS-1155 abs workspace

- Tests/Runner/EnvironmentTest.php
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PS-1512
> add row id to environment

- Tests/Runner/StateFileTest.php
- src/Docker/Runner/StateFile.php
Fixes: https://keboola.atlassian.net/browse/PS-1171
> StateFile: use new state api endpoint

- Tests/Controller/ActionControllerTest.php
- src/Controller/ActionController.php
- src/Resources/config/routing.yml
Fixes: https://keboola.atlassian.net/browse/PS-1554
> sync actions for branches

- composer.lock
https://keboola.atlassian.net/browse/PS-1564
> update output mapping to prefix tags on files

- apiary.apib
Fixes: https://keboola.atlassian.net/browse/PS-1556
> apiary - sync actions for branch

- composer.lock
follow up to https://github.com/keboola/input-mapping/pull/71
> fix: update IM to support YAML components in file mapping

- Tests/Docker/Configuration/ContainerConfigurationTest.php
- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- src/Docker/Configuration/Container.php
https://keboola.atlassian.net/browse/PS-1584
> PS-1584 Fix config validation for ABS workspace

- apiary.apib
Fixes: https://keboola.atlassian.net/browse/PS-1556
Minulý PR jsem trochu zvojtil a rozbilo to zobrazení sync akce a ukazovalo to jen akci pro dev mode.
Upravil jsem apiary file a vykoušel že se to už bude zobrazovat ok
> apiary - sync actions fixup

- Tests/Controller/ApiControllerTest.php
- Tests/Runner/CreateBranchTrait.php
- Tests/Runner/SharedCodeResolverTest.php
- Tests/Runner/VariableResolverTest.php
- apiary.apib
- src/Controller/ApiController.php
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/SharedCodeResolver.php
- src/Docker/VariableResolver.php
- src/Job/Executor.php
- src/Resources/config/routing.yml
https://keboola.atlassian.net/browse/PS-1558
feat: resolve branch shared code
feat: resolve branch variables
feat: add endpoint to resolve branch configuration
> [PS-1558] Dev/Prod mode variables + shared code

- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- composer.json
- composer.lock
- src/Docker/Runner/DataLoader/DataLoader.php
fix: table folder https://keboola.atlassian.net/browse/PS-1654
fix: table & file mapping https://keboola.atlassian.net/browse/PS-1653 
follow up to https://github.com/keboola/input-mapping/pull/83
> ABS mapping fixes

- composer.lock
follow up to https://github.com/keboola/output-mapping/pull/74
https://keboola.atlassian.net/browse/PS-1664
> fix: update OM to fix unspecified destination

- composer.lock
https://keboola.atlassian.net/browse/PS-1792
> feat: allow exclude tags in source tags file mapping

- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- src/Docker/Runner/DataLoader/DataLoader.php
> PS-1789 load tables as files on feature

- composer.lock
https://keboola.atlassian.net/browse/PS-1798
> PS-1798 Update IO libs

- Tests/Controller/ApiControllerTest.php
- src/Controller/ApiController.php
https://keboola.atlassian.net/browse/PS-826
> PS-826 Validate request parameters in projectDailyStatsAction

- composer.json
- composer.lock
- src/Docker/Runner/DataLoader/DataLoader.php
https://keboola.atlassian.net/browse/PS-1726
> PS-1726 - Update workspace provider

- Tests/Runner/RunnerTest.php
- composer.lock
- src/Docker/Configuration/Container.php
- src/Docker/Runner/DataLoader/DataLoader.php
- fixes the bug where if `use_file_storage_only` was set and `table_files` was empty, it would throw an error.
- also updates IM to support `changed_since: some time` function for files
> PS-2115 fix empty table_files bug and update IM for changed_since update

- composer.lock
https://keboola.atlassian.net/browse/PS-2160
> feat: support overwrite flag on ABS workspaces

- Dockerfile
- Tests/BaseContainerTest.php
- Tests/Docker/Container/ContainerTest.php
- azure-pipelines.yml
- composer.lock
https://keboola.atlassian.net/browse/PS-1949
> composer 2.0

- Tests/RunnerPart2/BranchedWorkspaceTest.php
- azure-pipelines.yml
- phpunit.sh
https://keboola.atlassian.net/browse/PS-2182
> PS-2182 Custom CI worker fixes

- Tests/Docker/Configuration/ConfigurationAdapterTest.php
- Tests/Docker/JobDefinitionParserTest.php
- composer.lock
https://keboola.atlassian.net/browse/PS-2232
> PS-2232 Update IM (support for `use_view` config)

- composer.lock
https://keboola.atlassian.net/browse/PS-2007
https://github.com/keboola/input-mapping/pull/102
> PS-2007 Update IM (table manifest write optimization)

- Tests/Executor/JobExecutorInlineConfigTest.php
- Tests/Executor/JobExecutorStoredConfigTest.php
- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PS-2307
> fix: remove docker prefix

- Tests/Controller/ApiControllerTest.php
- src/Controller/ApiController.php
https://keboola.atlassian.net/browse/PS-2311
> Don't run jobs when new queue is enabled

- composer.lock
https://keboola.atlassian.net/browse/PS-2378
follow up to https://github.com/keboola/input-mapping/pull/104
> Don't use clone loading when filtered alias is used

- Tests/Executor/JobExecutorInlineConfigTest.php
- Tests/Executor/JobExecutorInlineConfigWithConfigIdTest.php
- composer.lock
https://keboola.atlassian.net/browse/PS-2388
follow up to https://github.com/keboola/output-mapping/pull/87
> feat: tag staging files

- Tests/Executor/JobExecutorInlineConfigTest.php
- Tests/Executor/JobExecutorInlineConfigWithConfigIdTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PS-2352
feat: added KBC_STAGING_FILE_PROVIDER environment variable which contains type of file staging
docs update https://github.com/keboola/developers-docs/pull/175
> Staging file env

- src/Controller/ActionController.php
https://keboola.atlassian.net/browse/PS-2495
> fix: don't log context

- Tests/Runner/DataLoaderTest.php
- Tests/Runner/RunnerTest.php
- composer.json
- composer.lock
https://keboola.atlassian.net/browse/PS-2494
Release https://keboola.atlassian.net/browse/PS-815
> PS-2494 Update OM

- composer.lock
https://keboola.atlassian.net/browse/PS-2596
> PS-2596 Update OM

- Tests/Runner/DataLoaderTest.php
- Tests/RunnerPart2/OutputTest.php
- Tests/backend-specific-tests/Exasol/RunnerExasolTest.php
- composer.json
- src/Docker/Runner.php
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/DataLoader/NullDataLoader.php
- src/Docker/Runner/Output.php
- src/Docker/Runner/StorageState.php
Fixes: https://keboola.atlassian.net/browse/PS-2640
> Runner\Output - informations about input/output tables

- Tests/Docker/Runner/DataLoader/NullDataLoaderTest.php
- src/Docker/Runner/DataLoader/NullDataLoader.php
https://keboola.slack.com/archives/CQB468K63/p1632765344038400
> fix nullDataLoader

- composer.lock
https://keboola.atlassian.net/browse/PS-2857
> update key vault client

- Tests/ReflectionPropertyAccessTestCase.php
- Tests/Runner/RunnerTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- Tests/RunnerPart2/Runner2Test.php
- composer.json
- docker-compose.yml
- src/Docker/Component.php
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PS-2866
Depends on: https://github.com/keboola/sandboxes-api-php-client/pull/44
> PS-2866 Pass AZURE_STORAGE_CONNECTION_STRING to component

- Tests/Docker/MlflowProjectResolverTest.php
- Tests/RunnerPart2/Runner2Test.php
- src/Docker/MlflowProjectResolver.php
- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PS-2866
More strict check if the component should have access to MLflow:
- component has to have a mlflow-artifacts-access feature
- stack or project has to have a sandboxes-python-mlflow
- project must exist on sandboxes-api
> PS-2866 More strict check if the component should have access to MLflow

- Tests/Docker/Container/LoggerTest.php
- composer.lock
- src/Docker/Container.php
https://keboola.atlassian.net/browse/PS-629
https://keboola.atlassian.net/browse/PS-1775
> fix: handle invalid GELF messages gracefully

- composer.lock
- src/Controller/ApiController.php
https://keboola.atlassian.net/browse/PS-3125
fix link to new queue
> update object encryptor + other libs

- .gitignore
- Tests/Runner/ImageCreatorTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/CreditsChecker.php
- src/Docker/Runner.php
- src/Docker/Runner/ImageCreator.php
https://keboola.atlassian.net/browse/PS-3159
> optimize storage API calls

- composer.lock
Update https://github.com/keboola/storage-api-php-client/pull/767
> Update SAPI client (old queue)

- Tests/Runner/RunnerTest.php
- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PS-3167
> fix: clean workspace even in case of output mapping

- Tests/Docker/Container/ContainerErrorHandlingTest.php
- Tests/Docker/Container/ProcessTest.php
- src/Docker/Container.php
- src/Docker/Container/Process.php
https://keboola.atlassian.net/browse/PS-640
> trim long events before sanitization to save memory

- Tests/Docker/Container/LoggerTest.php
- composer.json
- src/Monolog/ContainerLogger.php
https://keboola.atlassian.net/browse/PS-3189
https://dev.azure.com/keboola-dev/docker-runner/_build/results?buildId=19948&view=logs&j=ee0b9186-f2c3-5fff-abdf-1153f3a044e4&t=0ec47aae-c95c-5739-e31c-c2270ae7309d&l=1442
> update deps to allow symfony 5.4

- Tests/BaseContainerTest.php
- Tests/BaseDataLoaderTest.php
- Tests/BaseRunnerTest.php
- Tests/Docker/Container/ProcessTest.php
- Tests/Docker/OutputFilterTest.php
- Tests/Docker/Runner/DataLoader/NullDataLoaderTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/ConfigFileTest.php
- Tests/Runner/DataLoaderMetadataTest.php
- Tests/Runner/DataLoaderTest.php
- Tests/RunnerPart2/BranchedWorkspaceTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- Tests/backend-specific-tests/ABS/DataLoaderABSTest.php
- Tests/backend-specific-tests/ABS/DataLoaderPersistentABSWorkspaceTest.php
- Tests/backend-specific-tests/Redshift/DataLoaderPersistentRedshiftWorkspaceTest.php
- Tests/backend-specific-tests/S3/DataLoaderS3Test.php
- src/Docker/Container/Process.php
- src/Docker/OutputFilter/OutputFilter.php
- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PS-640
- move all filtering into the OutputFilter class
- make limit for message length configurable
> make output filter limit configurable

- Tests/Docker/Runner/MlflowTrackingTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
- src/Docker/Runner/MlflowTracking.php
https://keboola.atlassian.net/browse/PS-3256
Pokud ma mit Job pristup k MLflow, pridame krome `MLFLOW_TRACKING_URI` i `MLFLOW_TRACKING_TOKEN`.
> PS-3256 MLflow tracking token

- Tests/Docker/Runner/MlflowTrackingTest.php
https://keboola.atlassian.net/browse/PS-3256
V mezicase nekdo udelal BC break na `OutputFilter` :wink:
> PS-3259 Fix MlflowTrackingTest

- composer.json
https://keboola.atlassian.net/browse/PS-3226
Update object encryptor version
> PS-3226 Update object encryptor version

- Tests/RunnerPart2/LimitsTest.php
- src/Docker/Runner/Limits.php
Zapomněl jsem změnit default backend ze starýho small na nový small!
follow up to https://github.com/keboola/docker-bundle/pull/650
> fix: change default backend to small

- composer.json
https://keboola.atlassian.net/browse/PS-3491
> Update SAPI client

- Tests/Docker/Configuration/ContainerConfigurationTest.php
- src/Docker/Configuration/Container.php
Fixes: https://keboola.atlassian.net/browse/PS-3450
> Docker/Configuration/Container - artifacts run section

- Tests/Runner/Docker/OutputFilter/NullFilterTest.php
- src/Docker/OutputFilter/MinimalFilter.php
https://keboola.atlassian.net/browse/PS-3423
Potřebuju sem https://github.com/keboola/runner-sync-api/blob/b864a494c1fb9c27370f239f555f18f4170fb994/src/Controller/ActionController.php#L181 strčit něco jinýho než NullFilter, aby to ofiltrovalo tu dementní hlášku
> add minimal filter

- Tests/BaseContainerTest.php
- Tests/BaseImageTest.php
- Tests/BaseRunnerTest.php
- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
- Tests/Docker/Image/ImageBuilderTest.php
- Tests/Docker/Image/ImageBuildingTest.php
- Tests/Docker/Image/QuayIORepositoryTest.php
- Tests/Docker/ImageTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/ConfigFileTest.php
- Tests/Runner/ImageCreatorTest.php
- Tests/Runner/RunnerTest.php
- Tests/RunnerPart2/BranchedWorkspaceTest.php
- Tests/RunnerPart2/StateFileTest.php
- composer.json
- src/Docker/Image.php
- src/Docker/Image/AWSElasticContainerRegistry.php
- src/Docker/Image/Builder/ImageBuilder.php
- src/Docker/ImageFactory.php
- src/Docker/JobScopedEncryptor.php
- src/Docker/Runner.php
- src/Docker/Runner/Authorization.php
- src/Docker/Runner/ImageCreator.php
- src/Docker/Runner/StateFile.php
https://keboola.atlassian.net/browse/PS-3686
Depends on https://github.com/keboola/docker-bundle/pull/663 (phpstan)
Nechavam jako draft dokud nebude updatnute na produkcni verzi encryptoru.
> PS-3686 Upgrade to new ObjectEncryptor

- Tests/Docker/Configuration/ContainerConfigurationTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/Configuration/Container.php
Rozhodol som sa nechat to ako "shared", kedze je to tak uz vsade okrem tej konfiguracie a celkovo to dava trochu viac zmysel.
> PS-3695: Artifacts 'orchestration' -> 'shared' in configuration

- Tests/RunnerPart2/OutputTest.php
- composer.json
- src/Docker/Runner.php
- src/Docker/Runner/Output.php
- src/Docker/Runner/StorageState.php
Fixes: https://keboola.atlassian.net/browse/PS-3494
> Collect output metrics in docker bundle

- Tests/Runner/DataLoaderTest.php
- src/Docker/Runner/DataLoader/DataLoader.php
https://keboola.atlassian.net/browse/PS-3424
~The root cause however is that the isReusableWorkspace() actually attempts to create the workspace if it doesn't exist, which seems a bit difficult to fix to me :)~
The second version seems to be better
> Exasol paused server should be user error

- composer.json
https://keboola.atlassian.net/browse/PS-3719
Sry za promichani tech dependencies v `composer.json`, ale vsude jinde mame dependencies serazene a uz nekolikrat jsem si rikal, ze tady nam (mi?) to chybi :slightly_smiling_face:
> Allow keboola/storage-api-client ^13.4|^14.0

- Tests/Docker/JobDefinitionParserTest.php
- src/Docker/JobDefinitionParser.php
https://keboola.atlassian.net/browse/PS-3800
Jako nepodařilo se mi úplně zjistit jak se to dá udělat, ale zjevně se to nějak udělat dá
> handle null state

- Tests/Docker/BillingClientTest.php
- Tests/Docker/Image/ImageBuilderTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/DataLoaderTest.php
- composer.json
- src/Docker/Runner/Authorization.php
https://keboola.atlassian.net/browse/PS-3838
Follow up to https://github.com/keboola/oauth-v2-php-client/pull/11
> update oauth client

- src/Docker/Image/AWSElasticContainerRegistry.php
https://keboola.atlassian.net/browse/PS-3879
> add ecr client timeout

- src/Docker/Image/AWSElasticContainerRegistry.php
FIXES: https://keboola.atlassian.net/browse/PS-3954
Fix po https://github.com/keboola/docker-bundle/pull/682
https://keboola.slack.com/archives/C13CP6YMV/p1668414416009619
> Fix AWS SDK timeouts

- Tests/Runner/RunnerTest.php
- composer.json
- src/Docker/Runner.php
don't conceal original error on failure
> add more tests to write table on failure

- Tests/Runner/RunnerTest.php
- Tests/RunnerPart2/WorkingDirectoryTest.php
- src/Docker/Runner/WorkingDirectory.php
https://keboola.atlassian.net/browse/JQ-18
> don't ignore working directory normalization errors

- Tests/backend-specific-tests/ABS/DataLoaderPersistentABSWorkspaceTest.php
- Tests/backend-specific-tests/BigQuery/RunnerBigQueryTest.php
- Tests/backend-specific-tests/Exasol/RunnerExasolTest.php
- Tests/backend-specific-tests/GCS/RunnerGCSTest.php
- Tests/backend-specific-tests/Redshift/DataLoaderPersistentRedshiftWorkspaceTest.php
- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- Tests/backend-specific-tests/Teradata/RunnerTeradataTest.php
https://keboola.atlassian.net/browse/PST-645
> asynchronous delete workspace in tests

- Tests/RunnerPart2/StateFileTest.php
- Tests/backend-specific-tests/ABS/DataLoaderPersistentABSWorkspaceTest.php
- Tests/backend-specific-tests/BigQuery/RunnerBigQueryTest.php
- Tests/backend-specific-tests/Exasol/RunnerExasolTest.php
- Tests/backend-specific-tests/GCS/RunnerGCSTest.php
- Tests/backend-specific-tests/Redshift/DataLoaderPersistentRedshiftWorkspaceTest.php
- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- Tests/backend-specific-tests/Teradata/RunnerTeradataTest.php
- src/Docker/Runner/StateFile.php
https://keboola.atlassian.net/browse/PST-561
> Update state saving to new API calls

- Tests/Docker/Configuration/ContainerConfigurationTest.php
- src/Docker/Configuration/Container.php
Fixes: https://keboola.atlassian.net/browse/PST-402
> Container Configuration - ignore and remove extra keys for backend

- Tests/BaseImageTest.php
- Tests/BaseRunnerTest.php
- Tests/Docker/Container/LoggerTest.php
- Tests/Runner/StateFileTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- Tests/TestEnvVarsTrait.php
- phpstan-baseline.neon
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PST-790
> PST-790 KBC_COMPONENT_RUN_MODE

- Tests/Docker/JobDefinitionParserTest.php
- src/Docker/JobDefinitionParser.php
https://keboola.atlassian.net/browse/PST-788
> fix weird configurations handling

- Tests/BaseImageTest.php
- Tests/Docker/JobDefinitionParserTest.php
- Tests/Docker/JobScopedEncryptorTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/ConfigFileTest.php
- Tests/Runner/StateFileTest.php
- phpstan-baseline.neon
- src/Docker/JobDefinition.php
- src/Docker/JobDefinitionParser.php
- src/Docker/JobScopedEncryptor.php
- src/Docker/Runner.php
- src/Docker/Runner/DataLoader/WorkspaceProviderFactoryFactory.php
- src/Docker/Runner/StateFile.php
https://keboola.atlassian.net/browse/SOX-41
> support branch type encryption

- composer.json
Part of https://keboola.atlassian.net/browse/SOX-297
> composer: staging-provider >=6.0.4

- Tests/Runner/ArtifactsTest.php
- composer.json
- src/Docker/Runner.php
depends on https://github.com/keboola/artifacts/pull/17
and https://github.com/keboola/artifacts/pull/18
> Protected Branch support in artifacts

- Tests/Runner/RunnerTest.php
- phpstan-baseline.neon
- src/Docker/Runner/DataLoader/DataLoader.php
I wanted to fix https://keboola.atlassian.net/browse/PST-1046 because it was basically my oversight when adding `write-always`
> ES-102 fix processed tag fail (PST-1046)

- Tests/Docker/JobDefinitionTest.php
- Tests/Runner/ConfigFileTest.php
- Tests/Runner/RunnerTest.php
- Tests/RunnerPart2/OutputTest.php
- phpstan-baseline.neon
- src/Docker/JobDefinition.php
- src/Docker/Runner.php
- src/Docker/Runner/Output.php
Part of https://keboola.atlassian.net/browse/SOX-391
> Output - input variables

- src/Docker/Runner/DataLoader/DataLoader.php
Part of : https://keboola.atlassian.net/browse/PST-986
Pred mergem pak zmenim base branch na odina aby se nasadili oba PR soucasne.
> DataLoader - tables-definition is not needed for typed tables

- src/Docker/Runner/DataLoader/DataLoader.php
Fixes: https://keboola.atlassian.net/browse/SOX-368
> DataLoader::storeDataArchive - use getTableAndFileStorageClient

- Tests/Runner/DataLoaderMetadataTest.php
- Tests/Runner/DataLoaderTest.php
- Tests/backend-specific-tests/BigQuery/DataLoaderBigQueryTest.php
- Tests/backend-specific-tests/BigQuery/RunnerBigQueryTest.php
- azure-pipelines.yml
- composer.json
- phpstan-baseline.neon
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/DataLoader/WorkspaceProviderFactoryFactory.php
https://keboola.atlassian.net/browse/GCP-404
> Preparation for reusable BigQuery workspaces

- Tests/Runner/ConfigFileTest.php
- src/Docker/Runner/ConfigFile.php
https://keboola.atlassian.net/browse/PST-1090
> PST-1090: check image parameters misuse

- Tests/Runner/ConfigFileTest.php
- src/Docker/Runner/ConfigFile.php
https://keboola.atlassian.net/browse/PST-1090
> also check misues of nested image_paramters

- Tests/Runner/AuthorizationTest.php
- phpstan-baseline.neon
- src/Docker/Configuration/Container.php
- src/Docker/Runner/Authorization.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PST-1021
> PST-1021: fix (Authorization): remove oauth v3 condition

- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PST-1036
> log working directory

- Tests/Docker/Configuration/ContainerConfigurationTest.php
- Tests/backend-specific-tests/BigQuery/DataLoaderBigQueryTest.php
- src/Docker/Configuration/Container.php
- src/Docker/Runner/DataLoader/WorkspaceProviderFactoryFactory.php
https://keboola.atlassian.net/browse/GMT-139
> add region to workspace

- Tests/Runner/ConfigFileTest.php
- Tests/Runner/RunnerTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PST-1241
https://keboola.atlassian.net/browse/PST-1243
* Pridani `KBC_CONFIGVERSION` do ENV jobu
* Test ze `authorization.app_proxy` neskonci v configu jobu (ono to tak funguje out-of-box, protoze se vybiraji jen konkretni items z `authorization`, ale tak pro jistotu jsme na to hodil test, aby to nekdo omylem neotocil)
> PST-1241 `KBC_CONFIGVERSION` + `authorization.app_proxy`

- Tests/Runner/DataLoaderTest.php
- Tests/Runner/RunnerTest.php
- Tests/StorageApiHandler.php
- phpstan-baseline.neon
- src/Docker/RunCommandOptions.php
- src/Docker/Runner.php
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/DataLoader/DataLoaderInterface.php
- src/Docker/Runner/DataLoader/NullDataLoader.php
The method is supposed to be called from termination signal handler
fixes https://keboola.atlassian.net/browse/PST-1229
> Make cleanup available from the outside

- README.md
- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
- azure-pipelines.yml
- phpstan-baseline.neon
- src/Docker/Image/AWSElasticContainerRegistry.php
https://keboola.atlassian.net/browse/PST-1031
> check image format 

- Tests/Docker/Configuration/ImageConfigurationTest.php
- src/Docker/Configuration/Component.php
https://keboola.atlassian.net/browse/PST-1343
- feat: (Configuration/Component): add dataTypeSupport and allowedProcessorPosition
> PST-1343: add dataTypeSupport and allowedProcessorPosition to Component definition

- Tests/Runner/DataLoaderTest.php
- src/Docker/Runner/DataLoader/DataLoader.php
https://keboola.atlassian.net/browse/PST-1359
> [PST-1359] Pass DataTypesSupport to OM

- azure-pipelines.yml
- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PST-1770
Docasne pridani extra logu pro presnejsi urceni, kde se sekaji joby v CSAS. Po vyreseni je zase vyhodime.
> PST-1770 Temporarily add logs

- azure-pipelines.yml
- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PST-1770
Followup na https://github.com/keboola/docker-bundle/pull/745
Extra logy budeme posilat do `debugLogger`, ktery bude nakonfigurovany jen na `stdout`, nepujde do event jobu
> Pepa pst 1770 extra logs

- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
- src/Docker/Image/AWSElasticContainerRegistry.php
https://keboola.atlassian.net/browse/PST-307
> PST-307 user exception for image not found

- Tests/RunnerPart2/EnvironmentTest.php
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PST-1624
> Add KBC_DATA_TYPE_SUPPORT env

- Tests/Docker/Image/QuayIORepositoryTest.php
- Tests/Docker/ImageTest.php
- Tests/Runner/ImageCreatorTest.php
https://keboola.atlassian.net/browse/PST-1835
> tests: change quay image

- Tests/Docker/ComponentTest.php
- Tests/Docker/Configuration/ImageConfigurationTest.php
- src/Docker/Component.php
- src/Docker/Configuration/Component.php
https://keboola.atlassian.net/browse/PST-1374
> Add validation allowedProcessorPosition and supportDataTypes 

- azure-pipelines.yml
https://keboola.atlassian.net/browse/PST-1831
Srovnani namingu ENV, at nam tu nestraci control plane
> Fix CI ENV naming (no control plane)

- Tests/Runner/DataLoaderTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PST-1391
mělo by to splňovat - https://keboola.atlassian.net/wiki/spaces/ENGG/pages/3099787265/PENDING+RFC-2023-016+Native+Data+types+Take+2#None-dataTypesSupport
> support new DataTypes only when project has feature

- Tests/Runner/DataLoaderTest.php
- composer.json
https://keboola.atlassian.net/browse/PST-1396
> [PST-1396] tests for new native types - metadata, hints dataTypeSupport

- Tests/Runner/AuthorizationTest.php
- Tests/Runner/ConfigFileTest.php
- src/Docker/Runner/Authorization.php
https://keboola.atlassian.net/browse/PST-1869
Pro jistotu nenechavam propsat cely `authorization`, ale jen tu `app_proxy` cast.
> PST-1869 Pass `app_proxy` through authorization config

- src/Docker/Runner.php
https://keboola.atlassian.net/browse/PST-1770
Reverts https://github.com/keboola/docker-bundle/pull/745 & https://github.com/keboola/docker-bundle/pull/746
Odstraneni docasnych debug logu
> Revert "PST-1770 Temporarily add logs"

- Tests/Docker/ImageTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/Runner.php
Fixes: https://keboola.atlassian.net/browse/PST-1689
Naplnění resulti jobu i při chybě. Přidává se table list z IM a file stats z IM
> Runner - set input tables and files to output before component run

- composer.json
Fixes: https://keboola.atlassian.net/browse/PST-2051
Aktualizace OM https://github.com/keboola/output-mapping/releases/tag/24.26.0
stacilo udelat v runneru, ale hodil jsem to i sem, at to je pak vsude
> deps: Update "keboola/output-mapping" lib

- Tests/Runner/DataLoaderTest.php
- composer.json
- src/Docker/Runner/DataLoader/DataLoader.php
Part of https://keboola.atlassian.net/browse/PST-1468
> DataLoader - treat_values_as_null

- .dockerignore
- .github/pull_request_template.md
Vzniklo jako pozadavek v ramci https://keboola.atlassian.net/browse/PST-2298
> .github - PR template - no-dind

- Tests/Runner/DataLoaderTest.php
- Tests/RunnerPart2/EnvironmentTest.php
- Tests/backend-specific-tests/ABS/DataLoaderPersistentABSWorkspaceTest.php
- src/Docker/Runner/Environment.php
Jira: https://keboola.atlassian.net/browse/PST-2467
Before asking for review, check the following:
---
Viz ticket. Melo by vyresit edge case s tim, kdy na novych native types vytvoritm konfiguraci, vypnu si native types a pustim komponentu
> Add KBC_DATA_TYPE_SUPPORT env only if native types are enabled

- Tests/Docker/Configuration/Authorization/AuthorizationDefinitionTest.php
- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
- Tests/Docker/ImageTest.php
- Tests/Runner/DataLoaderTest.php
- Tests/Runner/StateFileTest.php
- Tests/RunnerPart2/LimitsTest.php
- Tests/backend-specific-tests/ABS/DataLoaderPersistentABSWorkspaceTest.php
- Tests/backend-specific-tests/Redshift/DataLoaderPersistentRedshiftWorkspaceTest.php
- composer.json
- src/Docker/Configuration/Authorization/AuthorizationDefinition.php
- src/Docker/Configuration/Component.php
- src/Docker/Configuration/Container.php
- src/Docker/Configuration/Image.php
- src/Docker/Configuration/SharedCodeRow.php
- src/Docker/Configuration/State.php
- src/Docker/Configuration/Usage.php
- src/Docker/Configuration/VariableValues.php
- src/Docker/Configuration/Variables.php
- src/Docker/Runner/DataLoader/WorkspaceProviderFactory.php
https://keboola.atlassian.net/browse/PAT-260
Pridani `privateKey` do `authorization.workspace`. Pouziva se pro Snowflake key-pair auth.
> feat: Allow privateKey in workspace auth config
