keboola/docker-bundle

- Docker/Executor.php
- Job/Executor.php
- Resources/config/services.yml
- Tests/Docker/ExecutorTest.php
- Tests/Functional/FunctionalTest.php
Pokud spustím např. ex-adform napřímo pomocí `configData` se zašifrovanými credentials:
tak to šlape v pohodě. Pokud to samé uložím do konfigurace a spustím ji pomocí `config` parametru zřejmě se to nerozšifruje.
> Decrypt configuration stored configuraiton on execute

- Docker/Configuration/Container.php
- Docker/Configuration/Image.php
- Docker/Executor.php
- Docker/Image.php
- Docker/Image/DockerHub/PrivateRepository.php
- ENVIRONMENT.md
- Job/Executor.php
- Tests/Docker/ExecutorTest.php
Omylem jsem tam zamergoval zmenu parametru u executoru, tak je to trosku neprehledny, ale nejdulezitejsi zmena je tohle:
https://github.com/keboola/docker-bundle/compare/image-parameters?expand=1#diff-6b9751d70869d5428e86cc16d56c8655L178
a vola se to tady
https://github.com/keboola/docker-bundle/compare/image-parameters?expand=1#diff-3dcd57d4e048464e12486e837ab2e023L217
Parametry z image se tedy rozsifruji az v okamziku kdy se predavaji containeru (ne driv) a rozsfiruji se pouze v pripade, ze se ten container spusti na ostro.
testy:
https://github.com/keboola/docker-bundle/compare/image-parameters?expand=1#diff-eb3df0823d182793cd90f98635d7027eR924
> Image parameters

- Controller/ActionController.php
- Tests/Controller/ActionControllerTest.php
Info o to že akce skončila chybou je v message imho duplicitní a pokud tu chybu zobrazujeme v ui tak to reálnou hlášku která uživatele zajímá odsouvá dál:
> sync action error message

- Docker/Image/Builder/ImageBuilder.php
- Tests/Docker/ImageBuilderTest.php
krome toho fixnuti je tam jeste zmena v tom ze se to cachovani pro `version === master` vypne jenom v pripade ze to jde pres runtime.
> fix: disable cache for master branch in builder

- composer.lock
Obsahuje upravený deploy skript kterému je nově možné předat region a bucket ze kterého má konfiguraci sosnout https://github.com/keboola/syrup/commit/49e4a0e5a9f3c754067c2ae5dfdb56c417d5df09
Na syrup-queue už jsem to samé nasadil a šlape bez problému.
> syrup update - multi region support config

- Docker/Container.php
- Tests/Functional/ContainerErrorHandlingTest.php
Got a ticket that is not clear what is out of memory.
This will add part saying that out of memory is container.
> Make clear that out of memory is container

- Tests/Docker/ComponentTest.php
- Tests/Docker/Container/ContainerTest.php
- Tests/Runner/LimitsTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/Component.php
- src/Docker/Container.php
- src/Docker/Runner/Limits.php
- added `no-swap` feature to revert the new behavior
- removed device io limits, as they were not working properly (https://github.com/keboola/syrup-router/issues/118)
FIXES https://github.com/keboola/syrup-router/issues/118
> feat: swap

- Tests/Docker/Container/LoggerTest.php
- src/Docker/Container.php
fixes #334 
limit jsem dal na ~4000 znaku, protoze nemuzu uplne vyloucit, ze tam by se projevilo oriznuti na 8000 znaku v PT,  4000 pro samotny messagy by melo znamenat, ze se do 8000 vejde s rezervou i JSON
i tak je to vic jak 10x vic nez soucasna delka, takze by to melo vyresit #334 a dalsi experimenty s limitem zprav bych nechal na https://github.com/keboola/docker-runner-jobs
> longer exception messages

- Resources/config/services.yml
- composer.lock
- src/Service/StorageApiService.php
Reverts keboola/docker-bundle#367
Circular reference detected for service "syrup.storage_api", path: "syrup.listener.exception -> syrup.storage_api -> logger -> syrup.monolog.sapi_handler".  
https://jenkins.keboola.com/view/Docker%20Runner/job/PHPUnit%20-%20docker-bundle/707/console
nechapu to, ale je to rozbity
> Revert "feat: catch logged events from storage api client"

- Tests/BaseContainerTest.php
- Tests/Controller/ActionControllerTest.php
- Tests/Docker/Container/ContainerTest.php
- Tests/Docker/Container/LoggerTest.php
- Tests/Docker/Container/NetworkTest.php
- Tests/Runner/RunnerTest.php
- composer.lock
replaces https://github.com/keboola/docker-bundle/pull/370
> vendor update

- Tests/Runner/DataLoaderMetadataTest.php
- Tests/Runner/RunnerTest.php
- composer.json
- composer.lock
- src/Docker/Runner.php
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/DataLoader/DataLoaderInterface.php
- src/Docker/Runner/DataLoader/NullDataLoader.php
- src/Docker/Runner/Output.php
refactor: removed support for parallel-output-mapping-load feature
feat: deferred loads are now the only behavior
refactor: uploadTables now returns LoadTableQueue queue object instead of array of job ids
replaces https://github.com/keboola/docker-bundle/pull/386
> update output mapping take4

- Tests/Runner/StateFileTest.php
- src/Docker/Runner/StateFile.php
FIXES #393 
FIXES #315 
Celej blok na uložení state do configu/row jsem obalil try-catch s detekcí 404, která se mění na UserException
> fix: catch 404 in persistState

- Tests/Runner/DataLoaderTest.php
- Tests/Runner/RunnerConfigRowsTest.php
- Tests/Runner/RunnerTest.php
- Tests/Runner/StateFileTest.php
- composer.json
- composer.lock
- src/Docker/Runner.php
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/DataLoader/DataLoaderInterface.php
- src/Docker/Runner/DataLoader/NullDataLoader.php
- src/Docker/Runner/Output.php
- src/Docker/Runner/StateFile.php
Nejvíc zabíraj testy, `RunnerTest::testRunAdaptiveInputMapping` a `RunnerConfigRowsTest:testRunRowAdaptiveInputMapping`, který oba dělaj totéž, ale jedno na configu a druhé na row. Zbytek je celkem straightforward.
Trochu si nejsem jistej implementací v `Runner::runRow` a `StateFile::persistState`, ale v tom druhém případě by pomohlo od sebe rozdělit  `State` (načítání a ukládání z/do configu) a `ComponentState` (`config.json` na disku) a mohlo by to bejt zase čistý.
> feat: adaptive input mapping

- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
- Tests/Docker/ImageTest.php
- src/Docker/Image.php
fixes https://github.com/keboola/docker-bundle/issues/375
feat: do not pull image when tag and digest matches existing
fix: don't show 'Failed to get hash for image' as error, because it simply means that the image is not cached
fix: don't store fake 'err' digest to make digests reload after image is cached
> use image digests

- Tests/Executor/JobExecutorInlineConfigTest.php
- Tests/Runner/AuthorizationTest.php
- Tests/Runner/RunnerTest.php
- src/Docker/Runner/Authorization.php
Fixes: #440
Changes:
- Throw user exception if oauth_api version 2 is used
---
Najprv som malicko poladil testy, nech sa vsetko testuje s verziou 3. Potom som pridal user exception, ked sa zavola `getAuthorization ` a je tam `oauth_api.version` 2.
> Throw user exception if oauth_api version 2 is used

- Tests/Docker/ImageTest.php
Related to: https://github.com/keboola/docker-runner-router/issues/1
Changes:
- Add missing sudo command
---
Ten test sa choval hodne zvlastne. Samotny, na prvy raz presiel. No napriklad s `--filter ImageTest` uz nie.
> Add missing sudo command

- Tests/BaseRunnerTest.php
- src/Docker/Runner.php
Related: https://github.com/keboola/docker-runner-router/issues/3
Changes:
- remove "commandToGetHostIp" from constructor, try to load it from env
---
Toto sa mi zda lepsie.
Ak to nechceme posielat do mastra, rebasnem to  na tu druhu branch.
> Try to get "command to get host ip" from env, otherwise use default

- test-cf-stack.json
Related to: https://github.com/keboola/docker-runner-router/pull/2
Parametrizované jméno pro ECR aby nedocházelo ke kolizím.
> Testing Cloudformation template params

- src/Docker/Container.php
Related to: https://github.com/keboola/docker-runner-router/issues/15
FIXES: https://github.com/keboola/docker-bundle/issues/428
Nenašel jsem jestli se to nějak testuje, moc to ale asi nejde. Tohle bych pak mergnul do syrup-v11 pro dockerized runner a ten updatnul na tuhle změnu. Nebo by to mělo jít i do stávajícího masteru? pak bych to udělal obráceně a ten syrup-v11 nad to pak rebasnul po merge.
> Termination - restart job if docker daemon not available

- Tests/Controller/ActionControllerTest.php
- Tests/Controller/ApiControllerTest.php
- Tests/Executor/EncryptionTest.php
- src/Controller/ApiController.php
- src/Controller/PublicController.php
fixes incident https://keboola.slack.com/archives/CQB468K63/p1593113097024900?thread_ts=1592311989.039900&cid=CQB468K63
testy k tomu nejsou overim rucne po nasazeni na testing:
```
curl --location --request POST 'https://docker-runner.us-east-1.keboola-testing.com/docker/encrypt?componentId=test' \
--header 'Content-Type: application/json' \
--data-raw '{
"#a": "b"
}'
```
coz dneska konci chybou https://my.papertrailapp.com/events?q=a879a32517ac8716092efeadc3b6764c
> fix: legacy encrypt API call

- Tests/BaseDataLoaderTest.php
- Tests/Runner/DataLoaderMetadataTest.php
- Tests/Runner/DataLoaderTest.php
- Tests/backend-specific-tests/ABS/DataLoaderABSTest.php
- Tests/backend-specific-tests/S3/DataLoaderS3Test.php
- phpunit.xml.dist
https://keboola.atlassian.net/browse/PS-716
testy Tests/Runner/DataLoaderMetadataTest.php a Tests/Runner/DataLoaderTest.php a Tests/backend-specific-tests/ABS/DataLoaderABSTest.php a Tests/backend-specific-tests/S3/DataLoaderS3Test.php ukladaji data do ruznych bucketu a pouzivaji ruzne file tags - u toho ABS testu na tom nesejde, protoze pouziva jiny token, ale ty ostatni pouzivaji stejny token.
> tests: allow tests to run in parallel

- Tests/Docker/Image/AWSElasticContainerRegistryTest.php
https://keboola.atlassian.net/browse/PS-937
follow up to https://github.com/keboola/docker-bundle/pull/499
because this fails https://travis-ci.com/github/keboola/docker-runner-router/builds/185484287 because it uses different image for tests
> fix: image name can't be hardcoded

- src/Controller/ApiController.php
vyfailoval request na testing orchestraci https://connection.keboola.com/admin/projects/395/orchestrations/292003114/jobs/645913900 protoze sekce `admin` je v tokeninfo jen pokud je to master token
https://my.papertrailapp.com/groups/23635/events?focus=1259848640311205912&q=program%3Aapi-f4477108-320d-42af-ab67-b3e025943673&selected=1259848640311205912
testy by to chytili, kdyby se spoustely :(
> fix: accept non-admin tokens too

- Tests/Executor/JobExecutorStoredConfigTest.php
the assertion was wrong, but passing because the bucket and table existed. It existed because it's cleaned up before running the tests. When we changed branchname->branchid the bucket stopped to be cleaned and remained there until I cleaned it manually, which broke the tests.
> fix: test assertion

- composer.lock
follow up to https://github.com/keboola/input-mapping/pull/80
> fix: don't block configurations with empty processed tags

- src/Docker/Component.php
- src/Docker/Configuration/Component.php
Nová volba `no-internet` pro `network` config option. Developer Portal neřeším, je to pro ČSAS stack, kam se komponenty syncují manuálně. 
https://github.com/keboola/infrastructure-plugin-update-components/blob/900529c6e53d6f0d877dfcbef129ae439f42cf69/stacks/kbc-testing-azure-east-us-2.json#L80-L81
Naváže na to https://github.com/keboola/docker-runner-router/pull/121/.
https://keboola.atlassian.net/browse/SRE-1536
> feat: no-internet network option

- Tests/Runner/DataLoaderPersistentABSWorkspaceTest.php
- Tests/backend-specific-tests/ABS/DataLoaderPersistentABSWorkspaceTest.php
- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- composer.json
- composer.lock
- src/Docker/Runner/DataLoader/DataLoader.php
- src/Docker/Runner/DataLoader/WorkspaceProviderFactoryFactory.php
Řeší dohromady, protože jedno bez druhýho nejde (kvůli kontrole duplicitních workspace):
https://keboola.atlassian.net/browse/PS-2159
https://keboola.atlassian.net/browse/PS-2162
Dávám to jako draft, protože tam je dev závislost, závisí na https://github.com/keboola/staging-provider/pull/9
Plus mám teda vlastně jednu nejasnost - jestli to zapnem všude všem, nebo to budem nějak řešit přes fičuru (s tím souvisí failnutý tento test https://dev.azure.com/keboola-dev/docker-runner/_build/results?buildId=9302&view=logs&j=00172958-dc2f-5a07-7f65-b85e47f36adc&t=d87b4090-a97e-58d5-e3ab-66384d653296&l=2029 - protože workspace se nesmaže).
Já bych nakonec byl asi pro to, to zapnout všem, protože to je fíčura, která je stejně schovaná za sparkem a není běžně dostupná, i když je to trošku nečistý, …
> Persistent ABS workspaces

- Tests/Runner/RunnerConfigRowsTest.php
- Tests/Runner/RunnerTest.php
- Tests/RunnerPart2/BranchedWorkspaceTest.php
- Tests/RunnerPart2/OutputTest.php
- Tests/RunnerPart2/Runner2Test.php
- Tests/backend-specific-tests/ABS/RunnerAbsTest.php
- Tests/backend-specific-tests/Synapse/RunnerSynapseTest.php
- phpunit.xml.dist
- src/Docker/Runner.php
- src/Docker/Runner/Output.php
second part of https://keboola.atlassian.net/browse/PS-2120
změna spočívá v tom, že v runneru se Output předává jako reference (a ne result) a průběžně se do něj zapisuje, tzn. v případě chyby se zaznamená co zaznamenat šlo. To se testuje v tomto testu https://github.com/keboola/docker-bundle/pull/586/files#diff-6b2ec2ed1ae655ab48823af049f5cd7a36ef3171a033ab145afb826f3ef9cf86R1816 změny v okolních testech jsou jen změna v signatuře metody. 
required for https://github.com/keboola/job-runner/pull/56
> feat: record output continuously during execution

- Tests/RunnerPart2/EnvironmentTest.php
- src/Docker/Runner.php
- src/Docker/Runner/Environment.php
https://keboola.atlassian.net/browse/PS-2866
Po nasazeni `AZURE_STORAGE_CONNECTION_STRING` jsme pri testovani objevil, ze bude potreba jeste propisovat jeste `MLFLOW_TRACKING_URI`, kteoru MLflow klient pouziva k nalezeni serveru.
> PS-2866 Pass MLFLOW_TRACKING_URI

- Tests/RunnerPart2/LimitsTest.php
- src/Docker/Runner/Limits.php
https://keboola.atlassian.net/browse/PS-3480
Nové nastavení podle https://keboola.atlassian.net/wiki/spaces/KB/pages/2234941476/Dynamic+backend+size+per+job+Python+R#Option-2-(preferred-by-odin)%3A  za základní velikost transformační komponenty se nově považuje aktuálních 16GB
> Update limits according to changes

- Tests/Docker/ComponentTest.php
- Tests/Docker/Container/ContainerTest.php
- src/Docker/Component.php
- src/Docker/Container.php
fixes https://keboola.atlassian.net/browse/SRE-3888
Tato uprava zavadza featuru komponenty `container-tcpkeepalive-60s-override` ktora umoznuje prenastavit OS parameter ip stacku `net.ipv4.tcp_keepalive_time` na 60 sekund (default 2 hodiny).  Cele je to kvoli CSAS ktorym sa zasekava oracle ex niekde na network trafficu a rucnym testovanim sme zistili ze ten keepAlive parameter pomoze.
Tento parameter je mozne zmenit len cez parameter `docker run` commandu:
```
root@aks-jobs-20151051-vmss00000J:/# docker run --rm busybox sysctl net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_time = 7200
root@aks-jobs-20151051-vmss00000J:/# docker run --sysctl net.ipv4.tcp_keepalive_time=60 --rm busybox sysctl net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_time = 60
```
ak to menim vo vnutri …
> allow container tcp keepalive override to 60s via component feature

- Tests/Docker/Configuration/ContainerConfigurationTest.php
- Tests/Runner/ConfigFileTest.php
- Tests/Runner/DataLoaderTest.php
- src/Docker/Configuration/Container.php
- src/Docker/Runner/ConfigFile.php
Fixes https://keboola.atlassian.net/browse/PS-3919 + https://keboola.atlassian.net/browse/PS-3920
- Povolení `backend/context` a `workspace/account` v Container Configuration.
Testy padají viz https://keboola.slack.com/archives/CQB468K63/p1666704566912829 na spouštění testovací komponenty která nepovoluje extra fieldy v konfiguraci.
> ConfigFile  + Container Configuration

- src/Docker/Image/AWSElasticContainerRegistry.php
FIXES: https://keboola.atlassian.net/browse/PS-3954
Nastavení timeoutů pro STS klienta při assume credentials.
Vychází z https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html#assume-role-with-web-identity-provider Instance STS klienta by tam měla protéct přes parametry DefaultProvideru https://github.com/aws/aws-sdk-php/blob/cab6d4f830ce275a1742a3e35e2625917b006dd2/src/Credentials/CredentialProvider.php#L442
Nevím jak to vyzkoušet že se zkutečně správně zpropaguje ten klient.
> ECR - STS client timeouts

- Tests/RunnerPart2/WorkingDirectoryTest.php
- src/Docker/Image/AWSElasticContainerRegistry.php
- src/Docker/Runner/WorkingDirectory.php
https://keboola.slack.com/archives/C04GXMDK88M
Instalace do runneru: https://github.com/keboola/job-runner/pull/179
Historicky se nektere veci delaly skrze `docker run`, coz vyzaduje pullnout image z DockerHubu a zacalo delat problemy s rate limitem. Jelikoz ale Queue2 pousti kazdy job v izolovanem Podu, nemelo by to uz byt potreba.
> Remove unnecessary DinD usage

- Tests/Docker/Container/ContainerErrorHandlingTest.php
- Tests/Docker/Container/NetworkTest.php
- src/Docker/Component.php
https://keboola.atlassian.net/browse/PST-132
completely removed network override, it was used only in builder https://github.com/keboola/docker-bundle/commit/b59d3fe08f0d28b60e064a5ec03ea21eb052c171#diff-e6d5289c499e1eefd7ef3bfe208d20955ed61c7e6b35b7804a76fdc857fbb791L346
Follow up to https://github.com/keboola/docker-bundle/pull/681
> Update tests after builder removal

- Tests/Docker/Configuration/Authorization/AppProxyDefinitionTest.php
- Tests/Docker/Configuration/Authorization/AuthorizationDefinitionTest.php
- src/Docker/Configuration/Authorization/AppProxyDefinition.php
- src/Docker/Configuration/Authorization/AuthorizationDefinition.php
- src/Docker/Configuration/Container.php
https://keboola.atlassian.net/browse/PST-1242
Validace `authorization.app_proxy`.
* pokryva to pouze fieldy, ktery jsou soucasti specifikace, ale pocita se s tim, ze ruzny typy rules/providers muzou mit dalsi cusotm fieldy (`ignoreExtraKeys`)
* nevaliduje se `type` rules/providers, aby se sem nemuselo sahat pokazde, kdyz proxy prida podporu noveho identity providera atp.
Na testingu job s nastavenym `authorization.app_proxy` prosel https://connection.eu-west-1.aws.keboola.dev/admin/projects/51/queue/2432809
Plus to same jsem hodil jeste do `job-configuration`, ktery se pripravil v ramci no-dind iniciativy https://github.com/keboola/job-queue/pull/377
> PST-1242 Validator for authorization.app_proxy in config

- Tests/Docker/Configuration/Authorization/AppProxyDefinitionTest.php
- src/Docker/Configuration/Authorization/AppProxyDefinition.php
https://keboola.atlassian.net/browse/PST-1242
Followup na https://github.com/keboola/docker-bundle/pull/735
Pri testovani po releasu jsem jeste narazil, ze `allowed_roles` dela problem. V testech se to neprojevilo, protoze se to ukaze az kdyz se nechaji zvalidovat data, ktery validaci jednou prosly.
> PST-1242 Do not create empty `authorization.app_proxy.auth_rules[].allowed_roles` in config

- Tests/Docker/ComponentTest.php
- Tests/Docker/Configuration/ImageConfigurationTest.php
- src/Docker/Component.php
- src/Docker/Configuration/Component.php
https://keboola.atlassian.net/browse/PST-1343
- refactor (Component): use dataTypesConfiguration and processorConfiguration fields outside of data node
Validaci novejch fieldu pridame v ramci:
https://keboola.atlassian.net/browse/PST-1374
> PST-1343: dataTypesConfiguration and processorConfiguration in Component definition

- Tests/Runner/StateFileTest.php
- src/Docker/Runner/StateFile.php
https://keboola.atlassian.net/browse/PST-1888
Pokud ukladani state failne na chybejicim configu, zalogujem to jen jako warn a nechame job dobehnout.
Dojit k tomu muze, pokud za behu jobu neco smazne konfiguraci, coz nove chceme delat schvalne (delete app/sandboxu). Pokud by si config smaznul user omylem, za behu jobu a pozdeji ho treba obnovil, state nebude ulozeny tak jako tak. Rozdil je jen v tom, ze user ten omyl nove nemusi poznat uz u jobu ktery bezi, ale az kdyby ho chtel pustit znovu.
Ozkouseno na testingu
> PST-1888 Do not fail job if state can't be stored after job because config does not exist

- Tests/Runner/RunnerTest.php
- composer.json
Potřebuju updatnout IM  (^19) v rámci `job-runner`, ale blokuje mě require `dockerbundle` lib, která má ^18 verzi.
https://keboola.atlassian.net/browse/PST-525
> Update `keboola/input-mapping` lib

- Tests/Docker/Configuration/ContainerConfigurationTest.php
- Tests/Runner/DataLoaderTest.php
- src/Docker/Runner/DataLoader/DataLoader.php
Jira: https://keboola.atlassian.net/browse/PST-1468
Before asking for review, check the following:
---
V OM je to ošetřené, ale tady mi zůstala chybka. Nefungovalo to s prázdným pole. Prázdné pole v nastavení nahrazování prázdného stringu za null vypíná.
[PST-2298]: https://keboola.atlassian.net/browse/PST-2298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DataLoader - treat_values_as_null fixup for empty array

- Tests/Runner/DataLoaderTest.php
- src/Docker/Runner/DataLoader/DataLoader.php
Jira: https://keboola.atlassian.net/browse/PST-323
Before asking for review, check the following:
---
`cleanWorkspace()` se může zavolat opakovaně, díky tomu se pak loguje `Workspace not found` i u běžného user erroru z transformace
Upravil jsem to, aby se logovaly jen chyby, ktere nejsou 404
> DataLoader - ignore 404 ClientException on stagin provider cleanup

- Tests/Docker/Configuration/StateTest.php
- Tests/Runner/DataLoaderTest.php
- Tests/Runner/StateFileTest.php
- phpstan-baseline.neon
- src/Docker/Configuration/State.php
- src/Docker/Runner/StateFile.php
https://keboola.atlassian.net/browse/PST-2438
Povoleni dalsich root klicu mimo `component` a `storage` ve state konfigurace. Job Runner prepisuje jen puvodni `component` a `storage`. Zbytek state nechava byt. (puvodne to premlasklo cely state ve storage).
Jelikoz se state cte ze storage, upravi a pak zase cely zapise, muze se teoreticky stat, ze neco jineho upravit state v mezicase a runner pak tu zmenu zase prepise zpatky.
Ozkouseno s data appkou na testingu.
> PST-2438 Allow extra root keys in state

- composer.json
https://keboola.atlassian.net/browse/PAT-404
Update na latest `keboola/storage-api-client:^18.2.3`, ktery ma vyreseny prechod na stringovy ID event.
> PAT-404 Update SAPI client (main branch)

- composer.json
Jira: [AJDA-370](https://keboola.atlassian.net/browse/AJDA-370)
Connected to https://github.com/keboola/platform-libraries/pull/402
[AJDA-370]: https://keboola.atlassian.net/browse/AJDA-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: AJDA-370 bump output mapping to 27.0
